= Mooniak font projects documentation

== Glyphsets
Mooniak Glyphsets defines glyphsets for fonts made for Sri Lanka supporting Sinhala, Tamil and Latin scripts. 

Glyphsets are defined as follwoing; `basic, core, plus and pro` 

=== Basic 
Converted from ASCII-like legacy fonts to Unicode, dose not cover whole Sinhala Unicode block.

Fonts directly converted from non-Unicode legacy encodings such as FM (Fontmaster) font encoding.

=== Core
Unicode compliant, includes Sinhala numerals, Kunddlaiya, touch combinations

=== Plus
— Pro

— Bilingual (SIN+TML / SIN+LTN / TML+LTN / TML+LTN)
— Trilingual ()

Font project status
— actively-developed
— passively-maintained
— as-is
— experimental
— looking-for-maintainer
— deprecated



Font release channels 
—release ()
—dev (design stable, expected release glyphset complete, testing ready, features might be broken, spacing, kerning pending)
—alpha (Design explorations, drafts, ideas, broken glyphs, broken spacing )



**Sinhala Unicode block** 
  - Consonants 41
  - Independent vowels 16
  - Semi Consonants  2
  - Sinhala Pillam (Consonants modifier signs) 13					
  - Sinhala Archaic Numbers   - 20
  - Sinhala Astrological Numbers - 10
  - Kundaliya (Sinhala puncuation sign)

**Requierd ligature glyphs** 
  - Consonant-vowel ligatures
  - Half forms of ra and ya (rakaransaya, repaya, yansaya)

**Other glyphs** 
  - Ligated conjuncts (සංයෝග අකුරු sanyoga akuru)  
  - Touching consonant clusters (බැඳි අකුරු bandi akuru)
  - Rakar consonant clusters + modifier signs  
  - Ligated conjuncts + modifier signs
  - Touching consonants + modifier signs
  - Complex forms

**Stylistic alternates** 
  - Below base forms of pillam following Da forms (දා දැ දැ ඳෝ ද්‍ය ද්‍ය ද්‍යා ඤා ඤැ ඤැ ඥැ ඥැ ඥෝ) 
  - Historical Fa form (පf)
  - Historical kombuwa
  - 


***


## Mooniak Sinhala Core
- Sinhala Unicode block 
- Requierd ligature glyphs
- Touching consonant clusters implemented with dist feature
- Half forms of ra and ya (rakaransaya, repaya, yansaya)






***

### Sinhala fonts level definition by ICTA
Sinhala fonts are standardized into three different levels by ICTA, but this definition is only based on the functionality and it does not provide a clear identification of number of glyphs or coverage. We will try to define these here.			


**Level 1 fonts**
These fonts commonly used vowels, consonants and consonants with modifiers and they are intended to be used in mobile devices. This level supports special characters such as yansaya,rakaransaya and repaya and “ක්ෂ”**

**Level 2 fonts** 
These fonts shall have all the features of level one font and additionally support existing combination of Sinhala consonants with repaya. These fonts are intended for general applications such as documents and books.  

**Level 3 fonts**
These fonts support special characters and all combinations of strokes with conjuncts including “repaya+ispilla” combinations and touching conjuncts. These fonts fully support Pali and Sanskrit langauges and are intended for historic or classical Sinhala documents.